Unsuccessful attempt to test NVS with message DataFromPeer(SyncInfoSpec,...,...) **Not compiling**
Compilation error:

[error] /Users/Bruno/Dropbox/Code/Scorex/examples/src/test/scala/hybrid/NodeViewSynchronizerGenerators.scala:58:54: type mismatch;
[error]  found   : examples.hybrid.history.HybridSyncInfoMessageSpec.type
[error]  required: scorex.core.network.message.MessageSpec[Serializable]
[error] Note: examples.hybrid.history.HybridSyncInfo <: Serializable (and examples.hybrid.history.HybridSyncInfoMessageSpec.type <: scorex.core.network.message.SyncInfoMessageSpec[examples.hybrid.history.HybridSyncInfo]), but trait MessageSpec is invariant in type Content.
[error] You may wish to define Content as +Content instead. (SLS 4.5)
[error]     (ref, m, p, pchProbe, ncProbe, vhProbe, liProbe, sis)

It seems that, in order to solve this elegantly, I would have to make MessageSpec covariant w.r.t. Content, but this cannot be done, because Content occurs in an invariant position.